schema_version = 1
publish = true
id = "language.cot.pt-br"
locale = "pt-BR"
display_name = "Brazilian Portuguese"
xbox_language = 1
version = "1.0.0"
translation_version = "5.0"
credits_url = "https://oaleextraducoes.com/posts/2024/10/Crash-of-the-Titans/crash-of-the-titans-x360/"
