use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn rust_string(path: &Path) -> String {
    format!("{:?}", path.to_string_lossy())
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let resources_dir = manifest_dir
        .parent()
        .expect("src-tauri must have a launcher parent")
        .join("resources");
    let project_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("src-tauri must be inside the MojoRecomp project");
    let project_license = project_root.join("LICENSE");
    let summary = resources_dir.join("THIRD_PARTY_NOTICES.md");
    let licenses_dir = resources_dir.join("licenses");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", project_license.display());
    println!("cargo:rerun-if-changed={}", summary.display());
    println!("cargo:rerun-if-changed={}", licenses_dir.display());

    let mut license_files = fs::read_dir(&licenses_dir)
        .unwrap_or_else(|error| panic!("could not read {}: {error}", licenses_dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_file())
        .collect::<Vec<_>>();
    license_files.sort_by(|a, b| a.file_name().cmp(&b.file_name()));

    if license_files.is_empty() {
        panic!(
            "no third-party license files found in {}",
            licenses_dir.display()
        );
    }

    let mut generated =
        String::from("// Generated by launcher/src-tauri/build.rs. Do not edit.\n\n");
    generated.push_str(&format!(
        "pub const PROJECT_LICENSE: &str = include_str!({});\n",
        rust_string(&project_license)
    ));
    generated.push_str(&format!(
        "pub const THIRD_PARTY_NOTICE_SUMMARY: &str = include_str!({});\n",
        rust_string(&summary)
    ));
    generated.push_str("pub const THIRD_PARTY_LICENSES: &[(&str, &str)] = &[\n");
    for path in license_files {
        let name = path
            .file_name()
            .and_then(|value| value.to_str())
            .expect("license file name must be UTF-8");
        generated.push_str(&format!(
            "    ({name:?}, include_str!({})),\n",
            rust_string(&path)
        ));
    }
    generated.push_str("];\n");

    fs::write(out_dir.join("third_party_licenses.rs"), generated)
        .expect("could not generate embedded third-party license table");

    tauri_build::build()
}
