use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const PT_BR_TARGETS: [(&str, &str); 14] = [
    (r"cinematics\348a5480.p3d", "348a5480.p3d"),
    (r"cinematics\348a54bd.p3d", "348a54bd.p3d"),
    (r"cinematics\3eac4648.p3d", "3eac4648.p3d"),
    (r"cinematics\c1b269e4.p3d", "c1b269e4.p3d"),
    (r"package\L2_E4\a7e44a5e.p3d", "a7e44a5e.p3d"),
    (r"package\454d192.p3d", "454d192.p3d"),
    (r"package\59712a90.p3d", "59712a90.p3d"),
    (r"package\7a8185b0.p3d", "7a8185b0.p3d"),
    (r"package\7a88cba0.p3d", "7a88cba0.p3d"),
    (r"package\7efdcd91.p3d", "7efdcd91.p3d"),
    (r"package\97597d1b.p3d", "97597d1b.p3d"),
    (r"package\b4c85fe7.p3d", "b4c85fe7.p3d"),
    (r"package\c1e387c7.p3d", "c1e387c7.p3d"),
    (r"package\cdd70a8c.p3d", "cdd70a8c.p3d"),
];

fn rust_string(path: &Path) -> String {
    format!("{:?}", path.to_string_lossy())
}

fn collect_files(root: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, files);
        } else if path.is_file() {
            files.push(path);
        }
    }
}

fn generate_ptbr_bundle(project_root: &Path, out_dir: &Path) {
    let patch_root = project_root.join(".private").join("Patch PTBR");
    println!("cargo:rerun-if-changed={}", patch_root.display());

    let mut generated =
        String::from("// Generated by launcher/src-tauri/build.rs. Do not edit.\n\n");
    let mut discovered = Vec::new();
    collect_files(&patch_root, &mut discovered);

    let mut bundled = Vec::new();
    for (archive_path, file_name) in PT_BR_TARGETS {
        let matches = discovered
            .iter()
            .filter(|path| {
                path.file_name()
                    .and_then(|value| value.to_str())
                    .map(|value| value.eq_ignore_ascii_case(file_name))
                    .unwrap_or(false)
            })
            .collect::<Vec<_>>();
        if matches.len() == 1 {
            bundled.push((archive_path, matches[0].clone()));
        }
    }

    generated.push_str(&format!(
        "pub const BUNDLED_PT_BR_AVAILABLE: bool = {};\n",
        bundled.len() == PT_BR_TARGETS.len()
    ));
    generated.push_str("pub const BUNDLED_PT_BR_FILES: &[(&str, &[u8])] = &[\n");
    if bundled.len() == PT_BR_TARGETS.len() {
        for (archive_path, source) in bundled {
            generated.push_str(&format!(
                "    ({archive_path:?}, include_bytes!({}) as &[u8]),\n",
                rust_string(&source)
            ));
        }
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("bundled_ptbr.rs"), generated)
        .expect("could not generate embedded PT-BR resource table");
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let resources_dir = manifest_dir
        .parent()
        .expect("src-tauri must have a launcher parent")
        .join("resources");
    let project_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("src-tauri must be inside the MojoRecomp project");
    let project_license = project_root.join("LICENSE");
    let summary = resources_dir.join("THIRD_PARTY_NOTICES.md");
    let licenses_dir = resources_dir.join("licenses");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", project_license.display());
    println!("cargo:rerun-if-changed={}", summary.display());
    println!("cargo:rerun-if-changed={}", licenses_dir.display());

    let mut license_files = fs::read_dir(&licenses_dir)
        .unwrap_or_else(|error| panic!("could not read {}: {error}", licenses_dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_file())
        .collect::<Vec<_>>();
    license_files.sort_by(|a, b| a.file_name().cmp(&b.file_name()));

    if license_files.is_empty() {
        panic!(
            "no third-party license files found in {}",
            licenses_dir.display()
        );
    }

    let mut generated =
        String::from("// Generated by launcher/src-tauri/build.rs. Do not edit.\n\n");
    generated.push_str(&format!(
        "pub const PROJECT_LICENSE: &str = include_str!({});\n",
        rust_string(&project_license)
    ));
    generated.push_str(&format!(
        "pub const THIRD_PARTY_NOTICE_SUMMARY: &str = include_str!({});\n",
        rust_string(&summary)
    ));
    generated.push_str("pub const THIRD_PARTY_LICENSES: &[(&str, &str)] = &[\n");
    for path in license_files {
        let name = path
            .file_name()
            .and_then(|value| value.to_str())
            .expect("license file name must be UTF-8");
        generated.push_str(&format!(
            "    ({name:?}, include_str!({})),\n",
            rust_string(&path)
        ));
    }
    generated.push_str("];\n");

    fs::write(out_dir.join("third_party_licenses.rs"), generated)
        .expect("could not generate embedded third-party license table");
    generate_ptbr_bundle(project_root, &out_dir);

    tauri_build::build()
}
