#!/usr/bin/env python3
"""Generate link-only Xbox 360 import stubs for the current recompiled image.

This is deliberately a phase-0 tool.  It does not pretend that an unimplemented
kernel/XAM import succeeded; it only gives the linker a real symbol so the whole
translated image can be compiled and checked as one unit.  Boot-time HLE replaces
these stubs incrementally in runtime/kernel later.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "ppc" / "ppc_recomp_shared.h"
OUT = ROOT / "runtime" / "generated_import_stubs.cpp"
RUNTIME = ROOT / "runtime"


DEFINITION_PATTERNS = [
    re.compile(r"GUEST_FUNCTION_HOOK\(\s*__imp__(\w+)"),
    re.compile(r"GUEST_FUNCTION_STUB\(\s*__imp__(\w+)"),
    re.compile(r"^\s*PPC_FUNC\(\s*__imp__(\w+)\s*\)", re.MULTILINE),
]


def implemented_imports() -> set[str]:
    """Return imports that already have a real runtime definition.

    Once phase-1 HLE starts, generating a phase-0 stub for the same symbol would
    turn every correct implementation into a duplicate-symbol linker error.
    Scan runtime sources instead of keeping a second handwritten import list so
    this automatically follows the implementation as it grows.
    """
    found: set[str] = set()
    for path in sorted(RUNTIME.rglob("*.cpp")):
        if path.resolve() == OUT.resolve():
            continue
        # Build trees may contain generated copies and compiler probes. They are
        # not source-of-truth runtime implementations.
        if "build-smoke" in path.parts or "build" in path.parts:
            continue
        source = path.read_text(encoding="utf-8", errors="replace")
        for pattern in DEFINITION_PATTERNS:
            found.update(pattern.findall(source))
    return found


def main() -> None:
    if not SHARED.is_file():
        raise SystemExit(f"missing {SHARED}; run XenonRecomp first")

    text = SHARED.read_text(encoding="utf-8", errors="replace")
    names = re.findall(r"PPC_EXTERN_FUNC\(__imp__(\w+)\);", text)
    if not names:
        raise SystemExit("no __imp__ imports found in ppc_recomp_shared.h")

    # Keep first occurrence order.  It mirrors the image's symbol table and makes
    # generated diffs useful after a fresh recompilation.
    names = list(dict.fromkeys(names))
    implemented = implemented_imports()
    names = [name for name in names if name not in implemented]

    body = [
        "// Generated by tools/gen_link_stubs.py. Do not edit by hand.",
        "// Unimplemented imports are hard boot gates: they name themselves and",
        "// unwind the probe rather than silently manufacturing a return value.",
        "",
        '#include "ppc_recomp_shared.h"',
        '#include "kernel/unimplemented.h"',
        "",
    ]

    for name in names:
        body += [
            f"PPC_FUNC(__imp__{name}) {{",
            f'    MojoRecompRaiseUnimplementedImport("{name}", ctx.lr);',
            "}",
            "",
        ]

    output = "\n".join(body)
    current = OUT.read_text(encoding="utf-8", errors="replace") if OUT.is_file() else None
    if current != output:
        OUT.write_text(output, encoding="utf-8", newline="\n")
        status = "generated"
    else:
        status = "unchanged"
    print(
        f"{status} {len(names)} import stubs, skipped {len(implemented)} "
        f"runtime implementations -> {OUT}"
    )


if __name__ == "__main__":
    main()
